/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.susana.GUI;

import com.susana.Entidades.Parte;
import com.susana.Entidades.Transportista;
import com.susana.Entidades.Viaje;
import com.susana.LogicaNegocio.ViajesLN;
import com.susana.DAO.PartesDAO;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author acer
 */
public class VentanaViajes extends javax.swing.JFrame {

    ViajesLN partes;
    Transportista tr;
    Viaje vj;
    private DefaultTableModel modeloDeTabla;

    /**
     * Creates new form Viajes
     */
    public VentanaViajes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Viajes = new javax.swing.JTable();
        jButton1VerPartes = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VIAJES");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, -1, -1));

        jTable1Viajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID VIAJE", "HORA SALIDA", "HORA LLEGADA", "MATRICULA VEHICULO", "TOTAL HORAS VIAJE", "NUM PARTE", "USUARIO", "FECHA "
            }
        ));
        jTable1Viajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1ViajesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1Viajes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 789, 290));

        jButton1VerPartes.setText("Ver viajes");
        jButton1VerPartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1VerPartesActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1VerPartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 100, -1));

        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

//TODO: VIAJES

    private void jButton1VerPartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1VerPartesActionPerformed
        modeloDeTabla = (DefaultTableModel) jTable1Viajes.getModel();

        /*     try {
            Class.forName("java.sql.DriverManager");
            Connection conexion = DriverManager.getConnection("jdbc:oracle:thin:@10.10.10.9:1521:db12102", "system", "oracle");

            Statement sentencia = conexion.createStatement();

            CallableStatement sql = null;

            for (int i = 0; i < modeloDeTabla.getRowCount(); i++) {
                modeloDeTabla.removeRow(i);
                i -= 1;
            }

            sql = conexion.prepareCall("{call LISTARVIAJES(?)}");

            sql.registerOutParameter(1, OracleTypes.CURSOR);
            sql.execute();

            ResultSet resul = (ResultSet) sql.getObject(1);
            while (resul.next()) {

                try {
                    vj = new Viaje();
                      vj.setUsuario(resul.getString(7));

                    vj.setIdViaje(Integer.parseInt(resul.getString(1)));
                    vj.setNumParte(Integer.parseInt(resul.getString(6)));
                    vj.setHoraSalida(localTime(resul.getTime(2)));
                    vj.setHoraLlegada(Double.parseDouble(resul.getString(3)));
                    vj.setMatricula(resul.getString(4));
                    vj.setFecha(resul.getDate(8));
                    vj.setTotalHorasViaje(Double.parseDouble(resul.getString(5)));

                    modeloDeTabla.insertRow(modeloDeTabla.getRowCount(),
                            new Object[]{vj.getIdViaje(), vj.getHoraSalida(), vj.getHoraLlegada(),
                                vj.getMatricula(), vj.getFecha(), vj.getUsuario(), vj.getTotalHorasViaje()});

                    if (modeloDeTabla.getRowCount() == 0) {
                        JOptionPane.showMessageDialog(this, "Viaje inexistente con los datos indicados");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (modeloDeTabla.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Parte inexistente con los datos indicados");
            }
            resul.close();
            sentencia.close();
            conexion.close();

        } catch (ClassNotFoundException cn) {
            cn.printStackTrace();

        } catch (SQLException e) {
            e.printStackTrace();
        }
         */

    }//GEN-LAST:event_jButton1VerPartesActionPerformed

    //OPCIÓN PARA SALIR DEL PROGRAMA
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    //VOLVER A GESTIÓN PARTES
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        VentanaGestionPartes va = new VentanaGestionPartes();
        va.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1ViajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1ViajesMouseClicked
        
    }//GEN-LAST:event_jTable1ViajesMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaViajes().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1VerPartes;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1Viajes;
    // End of variables declaration//GEN-END:variables
}
