package com.susana.GUI;

import com.susana.Entidades.CentrosHime;
import com.toedter.calendar.JDateChooser;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import oracle.jdbc.OracleTypes;
import java.awt.event.FocusEvent;
import javax.swing.JTextField;

/**
 *
 * @author acer
 */
public class VentanaGestiónCentros extends javax.swing.JFrame {

    CentrosHime c;

    /**
     * Creates new form VentanaGestiónUsuarios
     */
    public VentanaGestiónCentros() {
        initComponents();
        jTextField1inserNombreCentro.requestFocus();
        this.setLocationRelativeTo(null);
        dispose();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2Centros = new javax.swing.JTextPane();
        jButton3unCentro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1inserNombreCentro = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4unCentro = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jTextField1Nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1Telefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldProvincia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField1CalleCentro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldNumCalleCentro = new javax.swing.JTextField();
        jButton3Atras = new javax.swing.JButton();
        jButton3exit = new javax.swing.JButton();
        jButton3borrarTrab = new javax.swing.JButton();
        jButton3NuevoCentro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1CodigoPostal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField2Ciudad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Listado Centros");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 730, -1));

        jScrollPane2.setViewportView(jTextPane2Centros);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 48, 730, 170));

        jButton3unCentro.setText("Buscar centro");
        jButton3unCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3unCentroActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3unCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 240, -1));

        jLabel1.setText("    Insertar nombre centro para borrar/actualizar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 250, -1));

        jTextField1inserNombreCentro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1inserNombreCentro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1inserNombreCentroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1inserNombreCentroFocusLost(evt);
            }
        });
        jTextField1inserNombreCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1inserNombreCentroActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1inserNombreCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 240, 25));

        jScrollPane4.setViewportView(jTextPane4unCentro);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 89, 240, 100));

        jButton1.setText("Actualizar centro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 240, -1));

        jTextField1Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1NombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 240, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 240, -1));

        jLabel4.setText("Teléfono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        getContentPane().add(jTextField1Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 131, -1));

        jLabel5.setText("Provincia");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));
        getContentPane().add(jTextFieldProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 260, -1));

        jLabel10.setText("Calle");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));
        getContentPane().add(jTextField1CalleCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 300, -1));

        jLabel12.setText("Número");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));
        getContentPane().add(jTextFieldNumCalleCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 70, -1));

        jButton3Atras.setText("Volver atrás");
        jButton3Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 370, -1, -1));

        jButton3exit.setText("Salir");
        jButton3exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3exitActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 410, 90, -1));

        jButton3borrarTrab.setText("Borrar centro");
        jButton3borrarTrab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3borrarTrabActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3borrarTrab, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 240, -1));

        jButton3NuevoCentro.setText("Nuevo centro");
        jButton3NuevoCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3NuevoCentroActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3NuevoCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 240, -1));

        jLabel3.setText("Código postal");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));
        getContentPane().add(jTextField1CodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 150, -1));

        jLabel13.setText("Ciudad");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));
        getContentPane().add(jTextField2Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Class.forName("java.sql.DriverManager");
            Connection conexion = DriverManager.getConnection("jdbc:oracle:thin:@10.10.10.9:1521:db12102", "system", "oracle");

            Statement sentencia = conexion.createStatement();

            CallableStatement sql = conexion.prepareCall("{call LISTACENTROS(?)}");
            sql.registerOutParameter(1, OracleTypes.CURSOR);
            sql.execute();

            ResultSet resul = (ResultSet) sql.getObject(1);
            Document otroDocumento = jTextPane2Centros.getStyledDocument();
            while (resul.next()) {
                try {
                    otroDocumento.insertString(otroDocumento.getLength(),
                            resul.getString(1) + " / " + resul.getString(2) + " / " + resul.getString(3) + " / "
                            + resul.getString(4) + " / " + resul.getString(5) + " / " + resul.getString(6)
                            + " / " + resul.getString(7) + " / " + resul.getString(8) + "\n", null);

                } catch (BadLocationException ble) {
                    ble.printStackTrace();
                }
            }
            resul.close();
            sentencia.close();
            conexion.close();
        } catch (ClassNotFoundException cn) {
            cn.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed
//ACCIONAMIENTO BUSCAR UN CENTRO, DESPUES DE INTRODUCIR NOMBRE CENTRO EN LA CASILLA HABILITADA PARA ELLO
    private void jButton3unCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3unCentroActionPerformed

        try {
            Class.forName("java.sql.DriverManager");
            Connection conexion = DriverManager.getConnection("jdbc:oracle:thin:@10.10.10.9:1521:db12102", "system", "oracle");

            Statement sentencia = conexion.createStatement();
            jTextField1inserNombreCentro.transferFocus();
            String centro = jTextField1inserNombreCentro.getText();

            CallableStatement sql = conexion.prepareCall("{call LISTARUNCENTRO(?, ?)}");
            sql.registerOutParameter(2, OracleTypes.CURSOR);
            sql.setString(1, centro);
            sql.execute();

            ResultSet resul = (ResultSet) sql.getObject(2);
            Document otroDocumento = jTextPane4unCentro.getStyledDocument();
            while (resul.next()) {
                try {

                    CentrosHime c = new CentrosHime();

                    c.setNombre(resul.getString(1));
                    c.setCalle(resul.getString(2));
                    c.setNumero(resul.getString(3));
                    c.setCodigoPostal(resul.getString(4));
                    c.setTelefono(resul.getString(5));
                    c.setCiudad(resul.getString(6));
                    c.setProvincia(resul.getString(7));
                    c.setIdCentro(Integer.parseInt(resul.getString(8)));

                    otroDocumento.insertString(otroDocumento.getLength(),
                            "NOMBRE: " + c.getNombre() + "\n" + "CALLE: " + c.getCalle() + "\n" + "NÚMERO: " + c.getNumero()
                            + "\n" + "CÓDIGO POSTAL: " + c.getCodigoPostal() + "\n" + "TELÉFONO: " + c.getTelefono()
                            + "\n" + "CIUDAD: " + c.getCiudad() + "\n" + "PROVINCIA: " + c.getProvincia()
                            + "NÚMERO CENTRO: " + c.getIdCentro() + "\n", null);
//
                    jTextField1CalleCentro.setText(c.getCalle());
                    jTextFieldNumCalleCentro.setText(c.getNumero());
                    jTextField1CodigoPostal.setText(c.getCodigoPostal());
                    jTextField1Telefono.setText(c.getTelefono());
                    jTextField2Ciudad.setText(c.getCiudad());
                    jTextFieldProvincia.setText(c.getProvincia());
                    //  jTextFieldIdCentro.setText(c.getIdCentro().toString());
                    jTextField1Nombre.setText(c.getNombre());

                    if (jTextPane4unCentro.getText().length() == 0) {
                        JOptionPane.showMessageDialog(this, "Centro inexistente con los datos indicados");
                    }

                } catch (BadLocationException ble) {
                    ble.printStackTrace();

                }

            }

            resul.close();
            sentencia.close();
            conexion.close();

        } catch (ClassNotFoundException cn) {
            cn.printStackTrace();

        } catch (SQLException e) {
            e.printStackTrace();

        }
        //fuente: aprenderaprogramar.com/foros/index.php?topic=1235.0
        if (jTextPane4unCentro.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Centro inexistente con los datos indicados");
        }
    }//GEN-LAST:event_jButton3unCentroActionPerformed

    private void jTextField1inserNombreCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1inserNombreCentroActionPerformed

    }//GEN-LAST:event_jTextField1inserNombreCentroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            Class.forName("java.sql.DriverManager");
            Connection conexion = DriverManager.getConnection("jdbc:oracle:thin:@10.10.10.9:1521:db12102", "system", "oracle");
//NOMBRE, CALLE, NUMERO, CODIGO_POSTAL, TELEFONO, CIUDAD, PROVINCIA, CENTRO_ID;
            String nombreC = jTextField1inserNombreCentro.getText();
            String nombreC2 = jTextField1Nombre.getText();

            String sql = "UPDATE CENTRO SET"
                    + " CALLE = ?, NUMERO = ?, CODIGO_POSTAL = ?,TELEFONO=?,"
                    + " CIUDAD=?, PROVINCIA=? WHERE NOMBRE = ?";
            PreparedStatement sentencia = conexion.prepareStatement(sql);
            sentencia.setString(1, jTextField1CalleCentro.getText());
            sentencia.setString(2, jTextFieldNumCalleCentro.getText());
            sentencia.setString(3, jTextField1CodigoPostal.getText());
            sentencia.setString(4, jTextField1Telefono.getText());
            sentencia.setString(5, jTextField2Ciudad.getText());
            sentencia.setString(6, jTextFieldProvincia.getText());
            sentencia.setString(7, jTextField1inserNombreCentro.getText());

            //  sentencia.setInt(10, Integer.parseInt(jTextFieldIdCentro.getText()));
            /*Si el nombre centro introducido para la búsqueda = al que ha encontrado, entonces ejecutar UPDATE
   si no, cambia toda la tabla
             */
            int filas = sentencia.executeUpdate();
            if (filas == 1) {
                JOptionPane.showMessageDialog(this, "Datos centro actualizados");

                jTextField1CalleCentro.setText("");
                jTextFieldNumCalleCentro.setText("");
                jTextField1CodigoPostal.setText("");
                jTextField1Telefono.setText("");
                jTextField2Ciudad.setText("");
                jTextFieldProvincia.setText("");
                jTextField1Nombre.setText("");

            } else {
                JOptionPane.showMessageDialog(this, "Datos centro NO actualizados");

            }

            sentencia.close();
            conexion.close();
        } catch (ClassNotFoundException cn) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, cn);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }    }//GEN-LAST:event_jButton1ActionPerformed
//VENTANA ADMINISTRADOR BORRANDO LA ANTERIOR
    private void jButton3AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3AtrasActionPerformed
        VentanaAdministrador vc = new VentanaAdministrador();
        vc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3AtrasActionPerformed

//SALIR DE PROGRAMA
    private void jButton3exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3exitActionPerformed
System.exit(0);    }//GEN-LAST:event_jButton3exitActionPerformed

    //ACCIONAMIENTO BORRAR TRABAJADOR
    private void jButton3borrarTrabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3borrarTrabActionPerformed
        try {
            Class.forName("java.sql.DriverManager");
            Connection conexion = DriverManager.getConnection("jdbc:oracle:thin:@10.10.10.9:1521:db12102", "system", "oracle");

            /*
            Clicando sobre el boton borrar trabajador, borra  el trabajador visualizado y que bien 
            se ha  buscado introduciendo DNI en la casilla habilitada para ello o se acaba de hacer nuevo y todavía está en pantalla
             */
            String sql = "DELETE FROM CENTRO WHERE NOMBRE=?";
            PreparedStatement sentencia = conexion.prepareStatement(sql);
            sentencia.setString(1, jTextField1inserNombreCentro.getText());

            int filas = sentencia.executeUpdate();
            if (filas == 1) {
                JOptionPane.showMessageDialog(this, "Datos centro borrados");
            } else {
                JOptionPane.showMessageDialog(this, "Indique nombre centro");

            }
            sentencia.close();
            conexion.close();
        } catch (ClassNotFoundException cn) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, cn);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);

            /*if (jTextPane4unCentro.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "centro inexistente con los datos indicados");
        }
            no me deja quitar la llave que esta en el espacio azul por eso tengo que dejarlo así
             */
        }       }//GEN-LAST:event_jButton3borrarTrabActionPerformed

    private void jTextField1NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1NombreActionPerformed

    }//GEN-LAST:event_jTextField1NombreActionPerformed
//CREAR NUEVO CENTRO
    private void jButton3NuevoCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3NuevoCentroActionPerformed
        int identificador = 0;
        try {
            Class.forName("java.sql.DriverManager");
            Connection conexion = DriverManager.getConnection("jdbc:oracle:thin:@10.10.10.9:1521:db12102", "system", "oracle");

            String sql = "INSERT INTO  CENTRO( NOMBRE, CALLE, NUMERO, CODIGO_POSTAL, TELEFONO, CIUDAD, PROVINCIA, CENTRO_ID) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement sentencia = conexion.prepareStatement(sql);

            sentencia.setString(1, jTextField1Nombre.getText());
            sentencia.setString(2, jTextField1CalleCentro.getText());
            sentencia.setString(3, jTextFieldNumCalleCentro.getText());
            sentencia.setString(4, jTextField1CodigoPostal.getText());
            sentencia.setString(5, jTextField1Telefono.getText());
            sentencia.setString(6, jTextField2Ciudad.getText());
            sentencia.setString(7, jTextFieldProvincia.getText());
            sentencia.setString(8, null);
            int filas = sentencia.executeUpdate();
            if (filas == 1) {
                JOptionPane.showMessageDialog(this, "Centro creado");
            } else {
                JOptionPane.showMessageDialog(this, "Error datos, introduzca datos correctos");

            }
            sentencia.close();
            conexion.close();
        } catch (ClassNotFoundException cn) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, cn);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3NuevoCentroActionPerformed

    private void jTextField1inserNombreCentroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1inserNombreCentroFocusGained

    }//GEN-LAST:event_jTextField1inserNombreCentroFocusGained

    private void jTextField1inserNombreCentroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1inserNombreCentroFocusLost

    }//GEN-LAST:event_jTextField1inserNombreCentroFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGestiónCentros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGestiónCentros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGestiónCentros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGestiónCentros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGestiónCentros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3Atras;
    private javax.swing.JButton jButton3NuevoCentro;
    private javax.swing.JButton jButton3borrarTrab;
    private javax.swing.JButton jButton3exit;
    private javax.swing.JButton jButton3unCentro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1CalleCentro;
    private javax.swing.JTextField jTextField1CodigoPostal;
    private javax.swing.JTextField jTextField1Nombre;
    private javax.swing.JTextField jTextField1Telefono;
    private javax.swing.JTextField jTextField1inserNombreCentro;
    private javax.swing.JTextField jTextField2Ciudad;
    private javax.swing.JTextField jTextFieldNumCalleCentro;
    private javax.swing.JTextField jTextFieldProvincia;
    private javax.swing.JTextPane jTextPane2Centros;
    private javax.swing.JTextPane jTextPane4unCentro;
    // End of variables declaration//GEN-END:variables
}
