/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.susana.GUI;

import com.susana.DAO.ConexionTest;
import com.susana.Entidades.Parte;
import com.susana.LogicaNegocio.PartesLN;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class VentanaCrearParteLogistica extends javax.swing.JFrame {

    private Integer numParte;

    /**
     * Creates new form VentanaCrearParteLogistica
     */
    public VentanaCrearParteLogistica() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    public void prepararParteAbierto(String usuario) {
        PartesLN pln = new PartesLN();
        Parte p = new Parte();
        p.setUsuario(usuario);
        p = pln.listarParteAbierto(p);
        jTextFieldUsuario.setText(p.getUsuario());
        if (p != null) {

            jTextFieldKmFinal.setText(String.valueOf(p.getKmFinal()));
            jTextField2GastosDieta.setText(String.valueOf(p.getGastoDietas()));
            jTextField1GasstoGastoil.setText(String.valueOf(p.getGastoGasoil()));
            jTextField1GastoAutopista.setText(String.valueOf(p.getGastoAutopista()));
            jTextField1Incidencias.setText(p.getIncidencias());
            jTextField1KmPrincipio.setText(String.valueOf(p.getKmPrincipio()));
            jTextField1GastosVarios.setText(String.valueOf(p.getGastosVarios()));
            jDateChooserFechaParte.setDate(p.getFecha());

            jTextFieldKmFinal.setEnabled(true);
            jTextField2GastosDieta.setEnabled(true);
            jTextField1GasstoGastoil.setEnabled(true);
            jTextField1GastoAutopista.setEnabled(true);
            jTextField1Incidencias.setEnabled(true);
            jTextField1KmPrincipio.setEnabled(true);
            jTextField1GastosVarios.setEnabled(true);
            jDateChooserFechaParte.setEnabled(true);

            numParte = p.getNumParte();

            jButtonNuevoParte.setEnabled(false);
            jBGuardarParte.setEnabled(true);
            jBCerrarParte.setEnabled(true);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField1KmPrincipio = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldKmFinal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1GastoAutopista = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1GastosVarios = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField2GastosDieta = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField1GasstoGastoil = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jDateChooserFechaParte = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jTextField1Incidencias = new javax.swing.JTextField();
        jButtonNuevoParte = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBCerrarParte = new javax.swing.JButton();
        jBGuardarParte = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PARTE DIARIO TRANSPORTISTA");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("USUARIO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, -1));

        jTextFieldUsuario.setEnabled(false);
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 310, 30));

        jLabel12.setText("KM. PRINCIPIO JORNAD");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 150, -1));

        jTextField1KmPrincipio.setEnabled(false);
        getContentPane().add(jTextField1KmPrincipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 150, -1));

        jLabel14.setText("KM. FINAL JORNADA");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 150, 30));

        jTextFieldKmFinal.setEnabled(false);
        getContentPane().add(jTextFieldKmFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 150, -1));

        jLabel4.setText("GASTO AUTOPISTA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 130, -1));

        jTextField1GastoAutopista.setEnabled(false);
        getContentPane().add(jTextField1GastoAutopista, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 180, -1));

        jLabel3.setText("GASTOS VARIOS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 150, -1));

        jTextField1GastosVarios.setEnabled(false);
        getContentPane().add(jTextField1GastosVarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 180, -1));

        jLabel13.setText("GASTOS DIETA");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jTextField2GastosDieta.setEnabled(false);
        getContentPane().add(jTextField2GastosDieta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 180, -1));

        jLabel15.setText("GASTO GASOIL");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jTextField1GasstoGastoil.setEnabled(false);
        getContentPane().add(jTextField1GasstoGastoil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 180, -1));

        jLabel17.setText("FECHA");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 80, -1));

        jDateChooserFechaParte.setEnabled(false);
        getContentPane().add(jDateChooserFechaParte, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 230, 30));

        jLabel5.setText("INCIDENCIAS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        jTextField1Incidencias.setEnabled(false);
        getContentPane().add(jTextField1Incidencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 240, 180));

        jButtonNuevoParte.setText("Nuevo Parte");
        jButtonNuevoParte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoParteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNuevoParte, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 240, 30));

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 70, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("En caso de visualizar un parte abierto, obligatorio cerrarlo para poder crear uno nuevo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 24, 570, 30));

        jBCerrarParte.setText("Cerrar Parte");
        jBCerrarParte.setEnabled(false);
        jBCerrarParte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarParteActionPerformed(evt);
            }
        });
        getContentPane().add(jBCerrarParte, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 140, 30));

        jBGuardarParte.setText("Guardar parte");
        jBGuardarParte.setEnabled(false);
        jBGuardarParte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarParteActionPerformed(evt);
            }
        });
        getContentPane().add(jBGuardarParte, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 140, 30));

        jButton1.setText("Añadir viaje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 120, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed

    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    /*

* Crea un nuevo parte y el usuario ya podría introducir datos

     */
    private void jButtonNuevoParteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoParteActionPerformed
        jTextField1KmPrincipio.setText("");
        jTextFieldKmFinal.setText("");
        jDateChooserFechaParte.setDate(null);
        jTextField1GasstoGastoil.setText("");
        jTextField1GastoAutopista.setText("");
        jTextField2GastosDieta.setText("");
        jTextField1GastosVarios.setText("");
        jTextField1Incidencias.setText("");
        jTextFieldUsuario.setText("");

        jTextField1KmPrincipio.setEnabled(true);
        jTextFieldKmFinal.setEnabled(true);
        jDateChooserFechaParte.setEnabled(true);
        jTextField1GasstoGastoil.setEnabled(true);
        jTextField1GastoAutopista.setEnabled(true);
        jTextField2GastosDieta.setEnabled(true);
        jTextField1GastosVarios.setEnabled(true);
        jTextField1Incidencias.setEnabled(true);
        jTextFieldUsuario.setEnabled(true);

        jButtonNuevoParte.setEnabled(false);
        jBGuardarParte.setEnabled(true);
        jBCerrarParte.setEnabled(false);


    }//GEN-LAST:event_jButtonNuevoParteActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed
//El usuario cierra el parte definitivamente
    private void jBCerrarParteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCerrarParteActionPerformed
        PartesLN pln = new PartesLN();
        Parte p = new Parte();
        p.setNumParte(numParte);
        p.setKmPrincipio(Double.parseDouble(jTextField1KmPrincipio.getText()));
        p.setKmFinal(Double.parseDouble(jTextFieldKmFinal.getText()));
        p.setFecha(new java.sql.Date(jDateChooserFechaParte.getDate().getTime()));
        p.setEstado("CERRADO");
        p.setGastoGasoil(Double.parseDouble(jTextField1GasstoGastoil.getText()));
        p.setGastoAutopista(Double.parseDouble(jTextField1GastoAutopista.getText()));
        p.setGastoDietas(Double.parseDouble(jTextField2GastosDieta.getText()));
        p.setGastosVarios(Double.parseDouble(jTextField1GastosVarios.getText()));
        p.setIncidencias(jTextField1Incidencias.getText());
        p.setValidar("NO");
        p.setUsuario(jTextFieldUsuario.getText());

        pln.actualizarDatos(p);

        jButtonNuevoParte.setEnabled(true);
        jBGuardarParte.setEnabled(false);
        jBCerrarParte.setEnabled(false);
    }//GEN-LAST:event_jBCerrarParteActionPerformed

    private void jBGuardarParteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarParteActionPerformed
        PartesLN pln = new PartesLN();
        Parte p = new Parte();
        if (numParte != null) {
            p.setNumParte(numParte);
        }
        p.setKmPrincipio(Double.parseDouble(jTextField1KmPrincipio.getText()));
        p.setKmFinal(Double.parseDouble(jTextFieldKmFinal.getText()));
        p.setFecha(new java.sql.Date(jDateChooserFechaParte.getDate().getTime()));
        p.setEstado("ABIERTO");
        p.setGastoGasoil(Double.parseDouble(jTextField1GasstoGastoil.getText()));
        p.setGastoAutopista(Double.parseDouble(jTextField1GastoAutopista.getText()));
        p.setGastoDietas(Double.parseDouble(jTextField2GastosDieta.getText()));
        p.setGastosVarios(Double.parseDouble(jTextField1GastosVarios.getText()));
        p.setIncidencias(jTextField1Incidencias.getText());
        p.setValidar("NO");
        p.setUsuario(jTextFieldUsuario.getText());

        if (numParte == null) {
            numParte = pln.insertarDatos(p);
        } else {
            pln.actualizarDatos(p);
        }

        jButtonNuevoParte.setEnabled(false);
        jBGuardarParte.setEnabled(true);
        jBCerrarParte.setEnabled(true);
    }//GEN-LAST:event_jBGuardarParteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaInsertarViajes iv = new VentanaInsertarViajes();
        iv.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearParteLogistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearParteLogistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearParteLogistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearParteLogistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCrearParteLogistica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCerrarParte;
    private javax.swing.JButton jBGuardarParte;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonNuevoParte;
    private com.toedter.calendar.JDateChooser jDateChooserFechaParte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1GasstoGastoil;
    private javax.swing.JTextField jTextField1GastoAutopista;
    private javax.swing.JTextField jTextField1GastosVarios;
    private javax.swing.JTextField jTextField1Incidencias;
    private javax.swing.JTextField jTextField1KmPrincipio;
    private javax.swing.JTextField jTextField2GastosDieta;
    private javax.swing.JTextField jTextFieldKmFinal;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
